title: Better YouTube Search Chrome Extension Developer Documentation
description: Better YouTube Search Chrome Extension Developer Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  The Void Repository: https://github.com/ChadWKirk/The-Void
